/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'netzwerg' at '12/5/14 8:31 AM' with Gradle 2.2
 *
 * @author netzwerg, @date 12/5/14 8:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
